- name: verify apache2
  shell: apache2ctl configtest 2>&1
  listen:
    - reload apache2
    - restart apache2

- name: reload apache2 via systemd
  systemd:
    name: apache2
    state: reloaded
    enabled: True
  listen: reload apache2

- name: restart apache2 via systemd
  systemd:
    name: apache2
    state: restarted
    enabled: True
  listen: restart apache2
