- name: Converge
  hosts: all
  become: True
  roles:
    - role: role-apache2
  vars:

    # apt packages to remove
    apache2_module_packages_removed:
      - libapache2-mod-dnssd
    # apt packages to install
    apache2_module_packages_installed:
      - libapache2-mod-security2

    # apache2 modules to disable
    apache2_disable_modules:
      - auth_basic
    # apache2 modules to enable
    apache2_enable_modules:
      - security2

    # Path of htusers file to create
    apache2_htpasswd_file: /etc/apache2/htpasswd/default
    # Htpasswd users to remove
    apache2_htpasswd_absent:
      - james
      - john
    # Htpasswd users to create
    apache2_htpasswd_present:
      - name: steve
        pass: secret

    # Vhosts to remove
    apache2_vhosts_absent:
      - 000-default
    # Vhosts to template and enable
    apache2_vhosts_present:
      - template: templates/etc/apache2/sites-available/000-my-default.conf.j2
        name: 000-my-default
