- name: install custom packages related to apache2
  apt:
    pkg: "{{ pkg_item }}"
    state: present
    update_cache: no
  with_items: '{{ apache2_module_packages_installed }}'
  loop_control:
    loop_var: pkg_item
  notify: restart apache2

- name: uninstall custom packages related to apache2
  apt:
    pkg: "{{ pkg_item }}"
    state: absent
    update_cache: no
  with_items: '{{ apache2_module_packages_removed }}'
  loop_control:
    loop_var: pkg_item
  notify: restart apache2

- name: disable apache2 modules
  command: a2dismod -f {{ mod_item }}
  with_items: '{{ apache2_disable_modules }}'
  loop_control:
    loop_var: mod_item
  changed_when: no
  notify: restart apache2

- name: enable apache2 modules
  command: a2enmod {{ mod_item }}
  with_items: '{{ apache2_enable_modules }}'
  loop_control:
    loop_var: mod_item
  changed_when: no
  notify: restart apache2

- name: disable apache2 vhosts
  command: "a2dissite {{ apache2_disable_vhost }}"
  args:
    removes: "/etc/apache2/sites-enabled/{{ apache2_disable_vhost }}.conf"
  notify: restart apache2
  with_items: '{{ apache2_disable_vhosts }}'
  loop_control:
    loop_var: apache2_disable_vhost
  changed_when: no
