---
- name: disable the apache2 default vhosts
  file:
    state: absent
    path: "/etc/apache2/sites-enabled/{{ apache2_default_vhost }}"
  with_items:
    - 000-default.conf
    - default-ssl.conf
  loop_control:
    loop_var: apache2_default_vhost
  notify: restart apache2

- name: template the default vhosts index page
  template:
    src: "var/www/html/index.html"
    dest: "/var/www/html/index.html"
    owner: www-data
    group: www-data
    mode: 0640

- name: configure global webroot for multi-domain LetsEncrypt
  when: apache2_enable_letsencrypt
  copy:
    src: etc/apache2/conf-enabled/letsencrypt.conf
    dest: /etc/apache2/conf-enabled/letsencrypt.conf
    owner: root
    group: root
    mode: 0644
  notify: reload apache2
