- name: install custom packages related to apache2
  apt:
    pkg: "{{ apache2_custom_pkg_item_install }}"
    state: present
    update_cache: no
  with_items: '{{ apache2_module_packages_installed }}'
  loop_control:
    loop_var: apache2_custom_pkg_item_install
  notify: restart apache2

- name: uninstall custom packages related to apache2
  apt:
    pkg: "{{ apache2_custom_pkg_item_uninstall }}"
    state: absent
    update_cache: no
  with_items: '{{ apache2_module_packages_removed }}'
  loop_control:
    loop_var: apache2_custom_pkg_item_uninstall
  notify: restart apache2

- name: disable apache2 modules
  command: a2dismod -f {{ apache2_mod_item_disable }}
  with_items: '{{ apache2_disable_modules }}'
  loop_control:
    loop_var: apache2_mod_item_disable
  changed_when: no
  notify: restart apache2

- name: enable apache2 modules
  command: a2enmod {{ apache2_mod_item_enable }}
  with_items: '{{ apache2_enable_modules }}'
  loop_control:
    loop_var: apache2_mod_item_enable
  changed_when: no
  notify: restart apache2

- name: disable apache2 vhosts
  command: "a2dissite {{ apache2_disable_vhost }}"
  args:
    removes: "/etc/apache2/sites-enabled/{{ apache2_disable_vhost }}.conf"
  notify: restart apache2
  with_items: '{{ apache2_disable_vhosts }}'
  loop_control:
    loop_var: apache2_disable_vhost
  changed_when: no
